### ISSUE TITLE
isPlayerRiichi conflict

### ISSUE THREAD

**Issue by potatoru** [Jimboom7/AlphaJong#1]
Hello. I use Tampermonkey with Chrome. I found that variable `isPlayerRiichi` in _parameters.js_ and function `isPlayerRiichi()` in _api.js_ have the same name and Chrome throw an exception. I commented out `isPlayerRiichi` variable (is it used?) and now it is working as expected.

Thank you for this script. I use it for gaining event points when very busy at work.

**Comment by Jimboom7** [comment]
Thanks for pointing this out!
The variable was indeed unused and is now removed.

Feel free to open more issues if you notice any problems, I'm glad someone is using my script :)
