### ISSUE TITLE
anyone know if the bot can do yakuman by itself?

### ISSUE THREAD

**Issue by Sopaigeah** [Jimboom7/AlphaJong#102]
do i need to put the 
EFFICIENCY = 1.0; // Lower: Slower and more expensive hands. Higher: Faster and cheaper hands. Default: 1.0, Minimum: 0 
in 0 ? like
EFFICIENCY = 0;
--
also if anyone have a recommended config please share it..
im sorry for posting this in Issues* i know its a question

**Comment by AcceleratorGodspower** [comment]
Can you please tell me your bot parameters? Preferably with a screenshot. And to what rank did you manage to reach?
