### ISSUE TITLE
Can you recommend me the best settings in this section to climb the rank as much as possible?

### ISSUE THREAD

**Issue by AcceleratorGodspower** [Jimboom7/AlphaJong#111]
![image](https://github.com/Jimboom7/AlphaJong/assets/134244511/2e26b090-10b9-46a0-905a-656b59e38544)

**Comment by Jimboom7** [comment]
In my experience the default values are the best. You can maybe lower the safety value for lower ranked lobbies.

**Comment by AcceleratorGodspower** [comment]
Thanks for the reply. Another question - is it normal that the bot almost never presses Chi, Kan and Pon? I'm a beginner, so I don't know. And I use a translator.

**Comment by Jimboom7** [comment]
> Thanks for the reply. Another question - is it normal that the bot almost never presses Chi, Kan and Pon? I'm a beginner, so I don't know. And I use a translator.

Yes, that is normal.
