### ISSUE TITLE
Alphajong Auto always operates with 4 seconds remaining.

### ISSUE THREAD

**Issue by fsgdgsfg** [Jimboom7/AlphaJong#113]
From the start of the game until the end of the game,

The hand pattern is always fixed to 4 seconds.

Since it is such an easy algorithm, it is inevitable that the account will be suspended.

The developer of this program is an idiot.

**Comment by Jimboom7** [comment]
There is a small random delay by default. You can tweak the number if you want, but I guess it's too late for that now since you got banned. Get rekt.
