### ISSUE TITLE
Proposals for strategy improvement

### ISSUE THREAD

**Issue by a2spxs** [Jimboom7/AlphaJong#13]
I've been testing a great project for a while. I am not a mahjong expert, but I am curious about a few things.

1) The AI is giving too much importance to dora.
This is an issue with the default values, and I think fixing it would make it better. However, it is difficult to find out the optimal value.

2)The AI is not very vigilant about Half Flush and Full Flush.
[Note: I often use 3P mode, so I don't know if this suggestion is valid for 4P mode.]
(I haven't read all the code.) For example, when another player declare pong, the danger level goes up, but it doesn't seem to be able to determine that anything else is a bit safer if they were the same type.
I think this is a difficult problem because the danger level is not given to each opposing player, but just taking this into account would make it more efficient in 3P mode.

**Comment by Jimboom7** [comment]
Hi,
1) the default values seem fine to me. You can change them for yourself however you like.
2) I just published v1.1.0 of the AI. Your proposal is implemented :) Thank you very much.
