### ISSUE TITLE
Problem with Little/Big Three Dragons.

### ISSUE THREAD

**Issue by c1410215** [Jimboom7/AlphaJong#14]
![image](https://user-images.githubusercontent.com/31218211/154951194-3a0a303a-0637-480c-b580-2edc38fb1cf6.png)

([RGWh] means Red/Green/White Dragon)
At the moment [R] was discarded, I do have [WhWhWh GG] in hand, which means little/big three dragons might be possible.
But the AI discarded the [R} which is not a normal player would do.
Also at last the AI switched from 2-side wait [3p/6p] to pair wait [5p/G], which is hard to understand for me.

**Comment by Jimboom7** [comment]
Hi, I just published v1.1.0 of the AI. I'm not sure if this problem in particular is fixed though, since there is not enough data on your issue (what exactly was the hand in the turn when the red dragon was discarded?). But the decisions of the AI are now better in general.
