### ISSUE TITLE
Problems about the bot's strategies

### ISSUE THREAD

**Issue by 6ftffyq3** [Jimboom7/AlphaJong#15]
I will post some very strange and unreasonable moves by your bot. For your reference only. The bot can be definitely improved with these problems solved (in some appropriate way).

**Comment by 6ftffyq3** [comment]
Notice: it is the last round (East 4) in an East game.

![1](https://user-images.githubusercontent.com/49231284/155027109-b6d87a95-c9bd-45b6-825e-a3af67705f21.png)
![2](https://user-images.githubusercontent.com/49231284/155027191-4553e423-d642-4b41-ab21-fc67e1ec534a.png)
![3](https://user-images.githubusercontent.com/49231284/155027216-a733196b-6062-4a75-a999-421f5e15e562.png)

There must be some problems with both your offense and defense strategies.

**Comment by 6ftffyq3** [comment]
![1](https://user-images.githubusercontent.com/49231284/155028344-67473948-9ea3-45a0-b0fe-519e0be6732b.png)
Why the bot ignored ittsu at such early stage?

**Comment by 6ftffyq3** [comment]
Notice: it is the last round (South 4).

![1](https://user-images.githubusercontent.com/49231284/155029758-251555a5-9934-4088-b30c-bef8bd094537.png)
So the bot thinks it should call riichi in this state? Any human players at expert level or above would refrain to do so.

Result:
![1](https://user-images.githubusercontent.com/49231284/155030094-9fac1bcd-04b5-40a4-bad4-9ba00f45f9c2.png)
![1](https://user-images.githubusercontent.com/49231284/155030331-3a063054-8d10-48e9-a7e3-0cbaabcf54e8.png)
![1](https://user-images.githubusercontent.com/49231284/155030551-4d8880aa-9535-4884-a9a3-7540fa566f89.png)

**Comment by Jimboom7** [comment]
Hi, I just published v1.1.0 of the AI. I used your issues as reference and they should be fixed now (there was a bug in the hand evaluation). The Riichi decision making was also improved, as well as general offense and defense decisions.
A note for further issues: Including the Debug String helps me a lot. To get it go to the correct turn in the replay and click the "Debug" button in the GUI (if the button is not visible you need to set the DEBUG_BUTTON parameter to true). That way I can recreate the state of the game exactly. A screenshot is also helpful.
