### ISSUE TITLE
“jiuzhongjiupai” means Kyūshu kyūhai (九種九牌) abortive draw

### ISSUE THREAD

**Issue by tml104** [Jimboom7/AlphaJong#18]
“jiuzhongjiupai” is Chinese Pinyin of Kanji 九種九牌. That means player can do this operation to restart the round if it already has over 9 types of yaochu at the very beginning.

I just wonder why they not use those words all in Japanese…

**Comment by Jimboom7** [comment]
Thank you very much for this information! I'm going to add a function that calls abortive draw when it happens.
