### ISSUE TITLE
No Riichi call

### ISSUE THREAD

**Issue by legomeaker101** [Jimboom7/AlphaJong#2]
i have been trying to get this script to work for a while now in chrome using tampermonkey and i finally got it to work, but the AI never calls for riichi is this intentional? or did i do something wrong? or do i just not understand the game?

also, i made a code for tampermonkey but didn't want to post it on greaseymonkey since i didn't write the code:
[Mahjong AI.user.js.zip](https://github.com/Jimboom7/AlphaJong/files/5106689/Mahjong.AI.user.js.zip)

**Comment by Jimboom7** [comment]
Sorry for the late answer. The AI should call for Riichi quite often. I just tested it once more and for me it seems to be working fine.
