### ISSUE TITLE
Second kita ignored

### ISSUE THREAD

**Issue by legomeaker101** [Jimboom7/AlphaJong#23]
First off: thank you, this tool has been amazing thanks for your hard work on it.
second: this issue was in 1.1.0 so it might have been patched in 1.2.0 but i had an issue where i got two kitas in a row and the ai called one but discarded the second Mahjong Soul Game Log: https://mahjongsoul.game.yo-star.com/?paipu=jkjnmr-ptxr409v-c68f-6hg8-fijm-ienkmwvswszr_a823809223_2

**Comment by Lucky-Trifolium** [comment]
Happened in `East-3 Turn-10`.
Definitely bug as the AI shouldn't have thrown it out of defense.

**Comment by Jimboom7** [comment]
It's difficult to recreate the problem, but I think I found a fix. The problem was related to the order how the bot processed the different operations. Now it will wait after calling Kita and reload the possible operations. That should hopefully fix the problem, but it's untested.
