### ISSUE TITLE
problem about kan

### ISSUE THREAD

**Issue by yuzuchann** [Jimboom7/AlphaJong#25]
When I meet open quad, it is OK. But if the kan I meet is a closed quad or a kakan(added open quad), the AI will not be able to deal with the situation. The result of it is to wait 25 seconds(20+5) and to discard the tile automatically.

**Comment by yuzuchann** [comment]
Oh, I attempted to correct the 1877th line to "discard()", then this problem seemed to be fine. Actually, ankan and addkan have the button of "decline", but somehow it would cause the above problem.

**Comment by Jimboom7** [comment]
Thank you for pointing this out. I realized what the problem is and fixed it now.
