### ISSUE TITLE
How do I set it to be aggressive?

### ISSUE THREAD

**Issue by muttti** [Jimboom7/AlphaJong#29]
I don't get points because I focus on defense. Thank you for letting me know about the offensive setting.

**Comment by Deadfarmer** [comment]
Go into the script and read the comments, friend. Change the constants yourself.

**Comment by muttti** [comment]
> 

I can't find a satisfactory setting

**Comment by Jimboom7** [comment]
To make the bot play more offensive you have to change these parameters:
FOLD_CONSTANT: Default is 10. To be more offensive raise this value, e.g. 15 or 20.
SAFETY_VALUE: Default is 0.5. To be more offensive lower this value, e.g. 0.3.

You have to figure out the "best" values yourself. For me the bot achieves the best results with the default defensive settings.
I hope that helps.
