### ISSUE TITLE
When calling chii for an existing tile on hand and trying to discard the duplicate called, the script bugs and hangs needing reboot

### ISSUE THREAD

**Issue by sataaa** [Jimboom7/AlphaJong#3]
The title says it all.

Example:
Your hand contains a pin sequence: 4 5 (non-dora) 6
The player to your left discards a pin 5 dora.
This might trigger a Chii call and the script then tries to discard the 5 (non-dora). Which is an illegal discard. The game bugs when the script tries to discard it (the tile disappears and everything freezes, needing to reload to rejoin the room).

**Comment by Jimboom7** [comment]
Thank you, I fixed it.
