### ISSUE TITLE
Kan stuck waiting

### ISSUE THREAD

**Issue by legomeaker101** [Jimboom7/AlphaJong#32]
at random intervals when getting a concealed KAN option the ai will get stuck until timeout without discarding or making the kan causing a very long wait with a limited example with ai bots: Mahjong Soul Game Log: https://mahjongsoul.game.yo-star.com/?paipu=jkjols-qvy01326-942c-6795-hada-crhljttts0r1_a823809223_2
![Screen Shot 2022-04-05 at 6 55 23 PM](https://user-images.githubusercontent.com/26052121/161869732-67c3320f-dcf0-435c-8768-8ef8f500ca23.png)
l
example with ai bo

**Comment by Jimboom7** [comment]
Hi, did you use the latest version of the bot? This should be fixed in v1.2.1.

**Comment by legomeaker101** [comment]
I am so sorry for this. I thought i had the latest but was on 1.2.0.
