### ISSUE TITLE
There seems to be a problem with the variable declaration.

### ISSUE THREAD

**Issue by dioarame** [Jimboom7/AlphaJong#33]
![image](https://user-images.githubusercontent.com/40052197/163330586-ae5fadd4-2c9f-4e85-bc69-0d583e07a787.png)
![image](https://user-images.githubusercontent.com/40052197/163331169-f8d30ea8-f94d-4386-ba57-bd9848ee2f8d.png)
![image](https://user-images.githubusercontent.com/40052197/163331121-9798a085-b2b6-44bf-9d59-3b39b918723a.png)
![image](https://user-images.githubusercontent.com/40052197/163331236-2308c680-aa0c-4e8a-a8c1-7b7160a3bc6c.png)
![image](https://user-images.githubusercontent.com/40052197/163331383-a952130e-14f2-4efb-97f6-6fce4a651f8f.png)

From line 278 to 494 and 652 to 656, Tempermonkey said eslint : no-undef warning message.

How can fix this warning?

Also, several parts deal with yaku have warning / error message.
Please check it and if I did wrong install, please reply.

**Comment by Jimboom7** [comment]
These warnings are perfectly normal. The code is referencing the game code of Mahjong Soul, which is unknown to Tampermonkey. That's why Tampermonkey thinks its undefined, but as soon as you are in the game the variables exist and everything should work fine.

**Comment by dioarame** [comment]
In addition, AI does not seem to take into account the other player's Big Three Dragon and the Chinitsu when they call several times. Is there any way to improve this?
