### ISSUE TITLE
I want you to add automatic participation in all rooms

### ISSUE THREAD

**Issue by Kamineko1978** [Jimboom7/AlphaJong#34]
I want you to add automatic participation in all rooms

**Comment by Deadfarmer** [comment]
The bot isn't ready to fight in Jade or Saint, the best score is only around M1. If you bot in Jade you're just asking to lose all your rank..

**Comment by Kamineko1978** [comment]
I will join you automatically？

**Comment by Kamineko1978** [comment]
futuristic

**Comment by legomeaker101** [comment]
I believe the option for auto join jade and saint rooms should be available (more as a future proof thing than an actually useful thing atm) but as deadfarmer said, the bot isn't ready to hold it's own in those

**Comment by Kamineko1978** [comment]
I'm testing in a triple room right now and I'm tinkering with the config to get a better 3P setting

In 2 days

![image](https://user-images.githubusercontent.com/47355146/163632418-96593141-5d93-461f-8e16-a4ee77653613.png)

**Comment by Kamineko1978** [comment]
![image](https://user-images.githubusercontent.com/47355146/163632460-a7069fc8-1fce-447a-b448-4543dd7daa87.png)
Contact me when I go to the next rank

**Comment by Jimboom7** [comment]
As @Deadfarmer and @legomeaker101 said, the bot is currently not good enough to consistently win in Jade Room or higher. Also the dropdown list is already pretty long.
But maybe it would be a good idea to add a "join same room" option which would check the current room at the end of the game and queue for it again after reloading.

**Comment by legomeaker101** [comment]
> Also the dropdown list is already pretty long.

spitballing here, but a solution for this could be having a variable for “rank” (and “rank-3” for sanma) if rank=master then only show gold and jade, if rank=novice only show bronze (this could be something editable by the user to avoid having to code in a check)

**Comment by Jimboom7** [comment]
I implemented the suggestion from @legomeaker101: The bot will now check which rooms are available for the current rank (even up to throne room). I also added the casual rooms.
I'll publish a new release in the next days after I've tested everything carefully.
