### ISSUE TITLE
对其中数值如何微调的疑问

### ISSUE THREAD

**Issue by MK8871** [Jimboom7/AlphaJong#35]
请问RIICHI_TILES_LEFT和WAITS_FOR_RIICHI两个数值大小的具体含义是什么？我是新手，如有打扰，甚是抱歉

**Comment by Jimboom7** [comment]
Sorry, I don't understand Chinese. My answer is translated with DeepL.

RIICHI_TILES_LEFT: Is the minimum amount of tiles (draws) that need to be left for calling Riichi. The default value is 6, this means the bot will not call Riichi when there are less than 6 tiles left.

WAITS_FOR_RIICHI: When the bot is tenpai and decides whether to call Riichi or not, it will check if the wait (待ち) is good or bad. This variable determines what a "good" or "bad" wait is - if the number of tiles the bot is waiting for is bigger than this variable it is considered a good wait. The exact algorithm for calling Riichi is complex, but to put it simply if this number is low the bot is more likely to call Riichi.

对不起，我不懂中文。我的回答是用DeepL。

RIICHI_TILES_LEFT：是指调用Riichi所需的最小牌数（平局）。默认值是6，这意味着当剩下的牌少于6张时，机器人将不会调用Riichi。

WAITS_FOR_RIICHI：当机器人天平决定是否调用Riichi时，它将检查等待（待ち）是好还是坏。这个变量决定了什么是 "好 "或 "坏 "的等待--如果机器人等待的牌数大于这个变量，就被认为是好的等待。调用Riichi的确切算法很复杂，但简单地说，如果这个数字较低，机器人就更有可能调用Riichi。

**Comment by MK8871** [comment]
十分感谢您的回复，你解释的非常清楚，我已经明白了，谢谢你


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月19日(周二) 晚上6:43
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Jimboom7/AlphaJong] 对其中数值如何微调的疑问 (Issue #35)




 
Closed #35.
 
&mdash;
