### ISSUE TITLE
感觉bot对于三元牌的优先级非常低啊

### ISSUE THREAD

**Issue by SunnySissi** [Jimboom7/AlphaJong#37]
![image](https://user-images.githubusercontent.com/92515662/166089849-cdfab313-98ad-4016-b466-09e9617564dc.png)
如图，这里应该切六万维持牌效，但是bot选择了切出红中

而且有时候感觉bot的危险意识有点太过，在可以听牌时选择了不听切安全牌（四暗刻一向听选择完全弃和😭）

**Comment by ms860309** [comment]
其實是可以調整parameter來改善是否要做大牌，我沒有深入了解code但是希望能加入parameter的上下限在註解!?
例如是ratio的意思然後
`var YAKU_VALUE = 0.5; // Default: 0.5,   (ignore Yaku) 0-10 (consider Yaku)`

**Comment by SunnySissi** [comment]
这部分说的应该是关于红宝牌的重要程度，0为完全忽略红宝牌。

AI有些时候的切牌感觉有些莫名奇妙，而且最近在雀杰1已经卡了两天了，基本都是吃一位四位，我在提高了安全牌优先级后仍然会经常放铳

**Comment by ms860309** [comment]
是說 要拚國士無雙最好起手應該9種9牌，但是會被handvalue<1.2而直接棄牌，不知道各位有什麼想法，當然一堆19跟單張字牌會覺得難打是正常拉

**Comment by Gengzi-Isu** [comment]
bot的各个数值上下限是多少啊，像是dora value之类的我一直以为是0～1

**Comment by SunnySissi** [comment]
国士是单独的逻辑，需要十张幺九牌bot才会去考虑做国士，你可以自己更改到9张，同样的还有默认的七对子需要五个对子才去靠七对子；但是我觉得对子这里还有待改进，因为bot似乎并不会去选择对对胡的役种，有时候手牌四对子可以多碰的时候bot也不会选择碰牌。

关于bot的数值上下限在注释里面都写了，都是0-1和0-10，数值越高表明bot更重视这一项，比如：
var DORA_VALUE = 0.4; // 0 -> ignore Dora. Default: 0.3
意思就是宝牌重要性，0为忽略宝牌，默认为0.3

**Comment by Jimboom7** [comment]
Sorry, I don't speak Chinese, but I translated it and can give you this answer now: 
[Version 1.3.0 was just released](https://github.com/Jimboom7/AlphaJong/releases/tag/v1.3.0). The AI should make better push/fold decisions now. If you think it still plays to safe you can adjust the parameter `SAFETY`: Set it to a lower value and the bot will play more offensive.

对不起，我不懂中文，但我翻译了，现在可以给你这个答案。
[1.3.0版本刚刚发布](https://github.com/Jimboom7/AlphaJong/releases/tag/v1.3.0)。AI现在应该会做出更好的推/折决定。如果你认为它仍然玩得很安全，你可以调整参数`SAFETY`。把它设置成较低的值，机器人就会发挥更大的进攻性。

**Comment by SunnySissi** [comment]
Thank you so much for the update, the new help mode really helped us a lot.
At present, AI can be promoted to rank4 (jade) smoothly, but after being
promoted to rank4, it usually loses a lot and returns to rank3 (gold).But I
don't think there is a big difference in the capability of players between
the two ranks. Normally, the level of AI should not be in a losing streak.
Is this normal?
