### ISSUE TITLE
Build Tool

### ISSUE THREAD

**Issue by yangruihan** [Jimboom7/AlphaJong#39]
Is there a build tool to pack all js source files to the release one file? I'm new to js, sorry to ask the stupid question.

**Comment by SunnySissi** [comment]
dose this is what you want?

https://github.com/Jimboom7/AlphaJong/releases/download/v1.2.1/AlphaJong_1.2.1.user.js

**Comment by yangruihan** [comment]
I think this is the packing result. But I don't know how to pack all source files to one file like this by myself. I just write a [Python Script](https://github.com/yangruihan/AlphaJong/blob/a09d4da30eecc0185d6fc039ceb14e8b92feb078/tool/build.py) to help me do this.
