### ISSUE TITLE
[Feature Suggestion] Keep mobile device awake

### ISSUE THREAD

**Issue by yangruihan** [Jimboom7/AlphaJong#48]
When I use AI on my mobile device‘s broswer, I often encounter the problem of device lock screen, we may need some logic to keep the mobile device awake.

When I saw this [library](https://github.com/richtr/NoSleep.js), I thought maybe we should do this too.

**Comment by Jimboom7** [comment]
I thought about this for a while, but to be honest I don't think it's worth the effort. If someone really needs it they can install another userscript with that functionality - and besides that there is always the option to just change the settings on your phone.
So I see that more as a standalone project and don't think it's a good idea to bloat our code with it.

**Comment by yangruihan** [comment]
You're right, I agree with you. So I will close this issue.

**Comment by keyarz** [comment]
> When I use AI on my mobile device‘s broswer, I often encounter the problem of device lock screen, we may need some logic to keep the mobile device awake.
> 
> When I saw this [library](https://github.com/richtr/NoSleep.js), I thought maybe we should do this too.

I'm not sure about this but you can try Play Lock on app store

**Comment by yangruihan** [comment]
> > When I use AI on my mobile device‘s broswer, I often encounter the problem of device lock screen, we may need some logic to keep the mobile device awake.
> 
> > 
> 
> > When I saw this [library](https://github.com/richtr/NoSleep.js), I thought maybe we should do this too.
> 
> 
> 
> I'm not sure about this but you can try Play Lock on app store

Thanks for your advice
