### ISSUE TITLE
Several suggestions to the new AI

### ISSUE THREAD

**Issue by n-agi** [Jimboom7/AlphaJong#49]
I've been testing your new reworked AI, and found some room for an improvement. I haven't used this AI before, but interested in your progress and your concept of AI. Some of those suggestions makes sense on my perspective, but I don't think the bot made a wrong decision.

Info: Master 1, tested on Jade's room
Game log: https://game.mahjongsoul.com/?paipu=jkjpls-sy5u049y-az5b-66id-fkgn-dhjjjpitsutw_a441025507_2

[East 1]
South didn't fold any of the `p` tiles, so folding `p` looks really dangerous on this side. For an efficiency(shaten) side, dropping hatsu is the best move, but we can't since hatsu is not dropped before. Keeping hatsu in hand almost has a same meaning of folding a full hand(holding only 1 hatsu at late game just means to give up), no-ten is what i prefer to choose on this game.

[South 1, First move]
Bot decided to drop 5p, which looks weird to me(+ trying to keep 1s in hand)

**Comment by Jimboom7** [comment]
[Version 1.3.0 is now released](https://github.com/Jimboom7/AlphaJong/releases/tag/v1.3.0), the two problems mentioned here should now work better. Thank you for your feedback!
