### ISSUE TITLE
Doesn't work in Majsoul+

### ISSUE THREAD

**Issue by Ledinax** [Jimboom7/AlphaJong#5]
[Structure of the folder](https://user-images.githubusercontent.com/17248251/120864961-65911680-c58d-11eb-88b4-ccafcc7cab52.png)
[Content of the json](https://user-images.githubusercontent.com/17248251/120863913-b273ed80-c58b-11eb-8144-c22ec771acaa.png)

Do I have to combine all scripts into one file?

**Comment by Jimboom7** [comment]
Hi, I compiled the code into one file, published ist as a release and updated the readme. [You can get it here](https://github.com/Jimboom7/AlphaJong/releases).
The installation should be much easier now. Let me know if it works!

**Comment by Ledinax** [comment]
Sorry for the big delay, forgot about this. It works perfectly now!
