### ISSUE TITLE
AFK detection triggered on firefox

### ISSUE THREAD

**Issue by keyarz** [Jimboom7/AlphaJong#54]
it will pop out AFK detection windows on firefox and activate auto draw & discard for you makes you lose the game

**Comment by Jimboom7** [comment]
Did you minimize the browser or use another tab while the game was running?
It's okay to use other programs while the bot operates, but if you minimize the game it will detect that.

**Comment by keyarz** [comment]
no i didn't minimize or change tab, i have dual monitor, it just not compatible with firefox not sure why? is my adblock addon blocking it? It run smooth on chrome which is what i using now

**Comment by cbrt729** [comment]
In my case, chiitoitsu strategy sometimes runs out of time and causes AFK warning, especially in tenpai.

**Comment by yangruihan** [comment]
> In my case, chiitoitsu strategy sometimes runs out of time and causes AFK warning, especially in tenpai.


This happens to me too

**Comment by Naelle2** [comment]
same in some rounds it takes too long for the bot to take a turn and make the afk timer pop up. But in the following rounds it doesnt happen
idk about chrome cuz the latest bot is super slow all around and freeze the game if i use it on chrome.

**Comment by legomeaker101** [comment]
there are two things i believe are causing this: the standard afk (which always happens and causes the bot to restart the page) or the took too long to act. this one might be one of 2 things: your computer is too slow for the bot (causing it to take too long with each turn) the bot isn’t active

**Comment by yangruihan** [comment]
These happen frequently on my mobile device

**Comment by keyarz** [comment]
> same in some rounds it takes too long for the bot to take a turn and make the afk timer pop up. But in the following rounds it doesnt happen idk about chrome cuz the latest bot is super slow all around and freeze the game if i use it on chrome.

try to activate the low spec mode in parameters

**Comment by keyarz** [comment]
> These happen frequently on my mobile device

How to use this in mobile? Mind to share?

**Comment by keyarz** [comment]
> there are two things i believe are causing this: the standard afk (which always happens and causes the bot to restart the page) or the took too long to act. this one might be one of 2 things: your computer is too slow for the bot (causing it to take too long with each turn) the bot isn’t active

I think find out what's the reason now, seems like it count as tabbing if I opening a new window with same browser, even though I'm not tabbing or minimizing.

**Comment by yangruihan** [comment]
> > These happen frequently on my mobile device
> 
> 
> 
> How to use this in mobile? Mind to share?

Android：you can use kiwi broswer which can use temparmonkey plugin. You can download from Google play

iOS: you can download Userscript safari plugin from App store,  which like temparmonkey allow to run user script on Safari

**Comment by Naelle2** [comment]
> > same in some rounds it takes too long for the bot to take a turn and make the afk timer pop up. But in the following rounds it doesnt happen idk about chrome cuz the latest bot is super slow all around and freeze the game if i use it on chrome.
> 
> try to activate the low spec mode in parameters

is this thread talking about the old ai? If yes i apologize my problem is for the new 1.3.0 beta. i have no problem with the old ai.

**Comment by yangruihan** [comment]
> 

There also is a parameter to control AI level `PERFORMANCE_MODE `, you can change it to make it faster.

**Comment by yangruihan** [comment]
> > > same in some rounds it takes too long for the bot to take a turn and make the afk timer pop up. But in the following rounds it doesnt happen idk about chrome cuz the latest bot is super slow all around and freeze the game if i use it on chrome.
> > 
> > 
> > try to activate the low spec mode in parameters
> 
> is this thread talking about the old ai? If yes i apologize my problem is for the new 1.3.0 beta. i have no problem with the old ai.

There also is a parameter to control AI level PERFORMANCE_MODE , you can change it to make it faster.

**Comment by keyarz** [comment]
> > > same in some rounds it takes too long for the bot to take a turn and make the afk timer pop up. But in the following rounds it doesnt happen idk about chrome cuz the latest bot is super slow all around and freeze the game if i use it on chrome.
> > 
> > 
> > try to activate the low spec mode in parameters
> 
> is this thread talking about the old ai? If yes i apologize my problem is for the new 1.3.0 beta. i have no problem with the old ai.

Where can i get the 1.3 version? I couldn't see it anywhere
I'm referring to 1.2.1 which is what I using now
![1 2 1](https://user-images.githubusercontent.com/21264195/168571605-2041c11e-698d-4321-9027-1537bf95f3a0.png)

**Comment by yangruihan** [comment]
> > > > same in some rounds it takes too long for the bot to take a turn and make the afk timer pop up. But in the following rounds it doesnt happen idk about chrome cuz the latest bot is super slow all around and freeze the game if i use it on chrome.
> 
> > > 
> 
> > > 
> 
> > > try to activate the low spec mode in parameters
> 
> > 
> 
> > is this thread talking about the old ai? If yes i apologize my problem is for the new 1.3.0 beta. i have no problem with the old ai.
> 
> 
> 
> Where can i get the 1.3 version? I couldn't see it anywhere
> 
> I'm referring to 1.2.1 which is what I using now
> 
> ![1 2 1](https://user-images.githubusercontent.com/21264195/168571605-2041c11e-698d-4321-9027-1537bf95f3a0.png)

You can find it in this PR https://github.com/Jimboom7/AlphaJong/pull/46

**Comment by keyarz** [comment]
After a day of testing, I can now confirmed if you covering the windows with any windows(maximized) on top, it will became AFK. 
Regardless what browser you're using
I'm on Win 10 64bit

**Comment by Jimboom7** [comment]
> After a day of testing, I can now confirmed if you covering the windows with any windows(maximized) on top, it will became AFK.
Regardless what browser you're using

Thank you for confirming this. I had the suspicion something like this might the problem, but I could never exactly determine it.
To be honest, I think it's not possible to prevent this by code. It seems to be the "Occlusion Tracking" feature which is mentioned [here](https://blog.chromium.org/2020/11/tab-throttling-and-more-performance.html), so it's not related to the game, but to the browser. I did a quick google search and there seem to be some ways to turn it off, I will check if that works and add it to the documentation.

> In my case, chiitoitsu strategy sometimes runs out of time and causes AFK warning, especially in tenpai.

That was related to a bug in version 1.2.1 and will be fixed when 1.3.0 is released.

**Comment by keyarz** [comment]
> > After a day of testing, I can now confirmed if you covering the windows with any windows(maximized) on top, it will became AFK.
> > Regardless what browser you're using
> 
> Thank you for confirming this. I had the suspicion something like this might the problem, but I could never exactly determine it. To be honest, I think it's not possible to prevent this by code. It seems to be the "Occlusion Tracking" feature which is mentioned [here](https://blog.chromium.org/2020/11/tab-throttling-and-more-performance.html), so it's not related to the game, but to the browser. I did a quick google search and there seem to be some ways to turn it off, I will check if that works and add it to the documentation.
> 
> > In my case, chiitoitsu strategy sometimes runs out of time and causes AFK warning, especially in tenpai.
> 
> That was related to a bug in version 1.2.1 and will be fixed when 1.3.0 is released.

I see, I wish this project will elevate to be a command prompt like bot in the future to get rid of this Haha
Btw, I really need that detail on the constants value so i can know what to change, i have no idea how to make it more offensive
because i don't know how far can the value go or which value to change.
