### ISSUE TITLE
Suggestion to display statistics calculation of bot

### ISSUE THREAD

**Issue by keyarz** [Jimboom7/AlphaJong#55]
Displaying statistics helping users to understand what's the bot thinking and how is these decision are made in real time.
So users can adjusting parameters in real time to fine tune the bot,
Also to find out whether the bot making wrong or right decision so it can be debug easily instead of watching replay.

Here's a project from [neighborhood](https://github.com/EndlessCheng/mahjong-helper) what i using to understand what's the bot thinking for reference.

![majsoul](https://user-images.githubusercontent.com/21264195/168733432-bebeb151-ed12-4460-b63d-af7993aad1f0.png)

**Comment by Jimboom7** [comment]
Logging is output to the browser console, you can open it with F12:
![image](https://user-images.githubusercontent.com/30753203/168742817-98657ada-2154-42be-8067-3b33814a6841.png)
