### ISSUE TITLE
There is some suggestion for Help Mode.

### ISSUE THREAD

**Issue by dioarame** [Jimboom7/AlphaJong#56]
Thanks for Great Update of 1.3.0 v!

There is no big problem, but I came up with a suggestion during the use.

Using Help Mode, visualization and information are very helpful.

However, when making a Richi declaration while using Help Mode, Bot only shows an overview of the log that considers which to be Discarded, and does not seem to show a specific Discard Tile.

Like this  :
 ["6s", "6s", "7s"]
Accept Richii!
(Because I am at outside work now, sorry for this is not accurate Log.)

I think it would be nice if the bot could indicate the Ricii declaration tile recommended.

Like this  :
 ["6s", "6s", "7s"]
Accept Richii with "6s"!

**Comment by yangruihan** [comment]
Thanks for the suggestion, I'll do it later :-)

**Comment by keyarz** [comment]
> Like this :
> ["6s", "6s", "7s"]
> Accept Richii with "6s"!

I think should replace "with" with "discard"
