### ISSUE TITLE
In some case danger value is not reasonable

### ISSUE THREAD

**Issue by murphymeng** [Jimboom7/AlphaJong#60]
![image](https://user-images.githubusercontent.com/7246104/169704375-43a174a5-101b-4c36-85a1-345ccbdfe8c4.png)
In this case, the debug string is 5z|577m22447p789s66z3p|||222555z342s||3z5s7z24m2s9p|4z99p7z1m|18p2216m9s3p|234z1s11p7z9m|0,0,0,0|1|1|41

![image](https://user-images.githubusercontent.com/7246104/169704428-0c115495-bdf5-4efa-b2d0-01cba5357354.png)
This is the result of priority calculation, the danger of 7p is too high(then it would be bigger than foldThreshold). I don't think it's reasonable because in this case, the flush should be considered into safety calculation. In fact discard 7p is the best choice when I run a AI test(akochan reviewer), it's far more safer than 7s and 8s.

Another issue is the efficiency of 3p should be better than 9s. Although both 3p and 9s are absolutely safe(现物), below is the analysis of akochan.

![image](https://user-images.githubusercontent.com/7246104/169704891-4069e074-6c6b-410f-9465-a87286649987.png)

**Comment by Jimboom7** [comment]
Thank you for the detailed information!
The bot already considered flush for defense, but it seems like it was not enough. I turned it up quite a lot and now the result looks a lot better:

> Hand:577m22447p789s66z3p  
> Would fold this hand above 88.99 danger for 7p discard.  
> Tile Priorities:  
> Overall: Value Open: <3130> Closed Value: <3478> Riichi Value: <8000> Shanten: <1>  
> 🀟: 7p: Priority: <205.327> Efficiency: <0.115> Yaku Open: <0.210> Yaku Closed: <0.398> Dora: <2.210> Waits: <0.318> Danger: <44.92>  
> 🀋: 5m: Priority: <154.925> Efficiency: <0.083> Yaku Open: <0.272> Yaku Closed: <0.516> Dora: <2.272> Waits: <0.194> Danger: <22.32>  
> 🀍: 7m: Priority: <104.202> Efficiency: <0.076> Yaku Open: <0.109> Yaku Closed: <0.378> Dora: <2.109> Waits: <0.124> Danger: <37.43>  
> 🀚: 2p: Priority: <-904.451> Efficiency: <-0.485> Yaku Open: <0.069> Yaku Closed: <0.071> Dora: <2.069> Waits: <0.000> Danger: <11.61>  
> 🀘: 9s: Priority: <-2184.224> Efficiency: <-0.797> Yaku Open: <0.135> Yaku Closed: <0.257> Dora: <2.135> Waits: <0.000> Danger: <3.35>  
> 🀛: 3p: Priority: <-2203.063> Efficiency: <-0.824> Yaku Open: <0.156> Yaku Closed: <0.157> Dora: <2.156> Waits: <0.000> Danger: <2.35>  
> 🀅: 6z: Priority: <-268.164> Efficiency: <-0.623> Yaku Open: <0.001> Yaku Closed: <0.071> Dora: <0.156> Waits: <0.000> Danger: <68.80>  
> 🀜: 4p: Priority: <-884.833> Efficiency: <-0.485> Yaku Open: <0.069> Yaku Closed: <0.071> Dora: <2.069> Waits: <0.000> Danger: <36.71>  
> 🀖: 7s: Priority: <-1671.465> Efficiency: <-0.839> Yaku Open: <0.161> Yaku Closed: <0.306> Dora: <2.161> Waits: <0.000> Danger: <515.50>  
> 🀗: 8s: Priority: <-1877.179> Efficiency: <-0.837> Yaku Open: <0.159> Yaku Closed: <0.304> Dora: <2.159> Waits: <0.000> Danger: <378.04>
