### ISSUE TITLE
Running the bot on phone browsers

### ISSUE THREAD

**Issue by Naelle2** [Jimboom7/AlphaJong#62]
when I tried to run the bot on phone, sometimes this screen pop up when I leave it for a while. 
![image](https://user-images.githubusercontent.com/101026745/169821494-8f7bfb9e-ab46-4866-ba54-6859cd1dfe14.png)
I wonder if there's a solution to this? My pc can't run the bot well even at 0 performance mode in the latest version

**Comment by Naelle2** [comment]
> Android? You can connect to your computer and enable usb debug mode so it won't lock the screen and detect leaving

yes android, I'll try to enable usb debug mode. I need to enable the option for the screen to stay awake?

**Comment by Naelle2** [comment]
> > My pc can't run the bot well even at 0 performance mode in the latest version
> 
> That's really surprising to me. Did it work for you in version 1.2.1 and before? Performance mode 2 in the latest version should basically be the same as the old version. Performance mode 1 and 0 should run way faster.

performace mode 1 is equivalent to 1.2.1 without low spec in my case. But Im trying to use phone to use best result as possible



> > > Android? You can connect to your computer and enable usb debug mode so it won't lock the screen and detect leaving
> > 
> > 
> > yes android, I'll try to enable usb debug mode. I need to enable the option for the screen to stay awake?
> 
> There is an option stay awake in debug menu, you can turn it on.
well it still happens, i already set screen timeout to 30 minutes originally
Ive been thinking, is playing on potrait mode probably the cause? I havent got an error after i lock my rotation on landscape mode, but i need to test it more because the occurence is so random before.

**Comment by keyarz** [comment]
not sure if [play lock](https://play.google.com/store/apps/details?id=com.brinktech.playlock&hl=en&gl=US) can help you

**Comment by Naelle2** [comment]
I dont think it is because the phone screen getting locked because I already enabled stay awake in the developer options

I think it might be a connection issue because after I switched mobile data provider it seemed to not occur again after 6 south match. but I'll conduct more tests to be sure
