### ISSUE TITLE
Suggestion for Help Mode : River Tile Color Distinction

### ISSUE THREAD

**Issue by dioarame** [Jimboom7/AlphaJong#70]
Thank you for the improved version of the bot.

Now that I think it shows stable performance, I would like to ask you a suggestion that I have been curious about before.

Is it possible to apply the color expression supported in Help mode to the discarded tiles on River?

As shown in Paifu, supporting the distinction between discarded tiles from hand and Tsumogiri tiles is expected to have a positive effect on the bot's computation and player's judgment.
(For example, if an opponent continues to play Tsumogiri and suddenly throws a tile away from his hand, he or she is conscious of Tenpai or its surrounding plaque)

This is thought to help create an environment in which the opponent can provide appropriate judgment to the player when the opponent is in Damaten or Call state.

**Comment by Jimboom7** [comment]
I implemented your suggestion. There is now a parameter ```MARK_TSUMOGIRI``` which you can set to true to enable the feature.
