### ISSUE TITLE
Discard the drawn tile first to prevent leaking information

### ISSUE THREAD

**Issue by ayssia** [Jimboom7/AlphaJong#73]
For example, my hand is 335789m234567p22s, and then I draw a 9m, bot will discard the 9m from my hand instead of the 9m that was just drawn. This will cause other players to know that I already have a 9m in my hand.

**Comment by yangruihan** [comment]
I think it would be better to change this to an option, there are some players who will deliberately discard their hands to confuse their opponents into thinking they haven't tenpai yet.
