### ISSUE TITLE
About the priority of the Akadora

### ISSUE THREAD

**Issue by lie5860** [Jimboom7/AlphaJong#75]
Pictures commented below

**Comment by ryuunoakaihitomi** [comment]
@lie5860 你这样问，至少还要贴一下牌谱。另外，其他家立直的时候，ai的选择都是**弃和**的。

**Comment by lie5860** [comment]
> 

意思是弃和的时候 丢红五条就是对的？

**Comment by lie5860** [comment]
![image](https://user-images.githubusercontent.com/30894657/176065766-cd676e28-de58-445b-9480-865e7caddc31.png)
场况是这样的

**Comment by ryuunoakaihitomi** [comment]
都弃了，早点丢还可以防止被其他人碰走

**Comment by lie5860** [comment]
> @lie5860 你这样问，至少还要贴一下牌谱。另外，其他家立直的时候，ai的选择都是**弃和**的。

是不是因为上家打了一个五条 所以到我这了五条是绝对安全的。所以从弃和的角度 优先出红五条比较好？

**Comment by ryuunoakaihitomi** [comment]
你都选择弃了，早点把最有价值的牌丢掉反而能够最大可能地使别人无法利用这张牌，我的想法是这样的。

**Comment by ryuunoakaihitomi** [comment]
不过好像也不对，因为反正对家也会振听。可能机器人的选择也确实有问题？

**Comment by Mazinrenown** [comment]
这牌看不懂时应该看ctrl+shift+j看一下后台ai是怎么判断的
不过弃和阶段效益都是负几万 也看不太明白就是了……
