### ISSUE TITLE
do not use alphajong higher than silver room

### ISSUE THREAD

**Issue by pepethejelly** [Jimboom7/AlphaJong#78]
[<img src=https://imgur.com/a/CddxWHB>](url)

bot script do stupid control make your account drop a lot score.

**Comment by Jimboom7** [comment]
The bot can achieve good results in gold and even Jade room. This is confirmed by multiple users.
Did you maybe change the settings? The default settings should work fine.
Anyway, at the moment I would not recommend to use the bot at all, as there is a high chance to get banned.
