### ISSUE TITLE
Think we should add a if about kokushi musou(thirteen orphans)关于国士无双的判断

### ISSUE THREAD

**Issue by Esingpawn** [Jimboom7/AlphaJong#81]
Think we should add a judgment about kokushi musou(thirteen orphans)
`var THIRTEEN_ORPHANS = 9; //Number of Honor/Terminals in hand to go for 13 orphans. Default: 10`
In actual operation, if you have three consecutive Nan (South), or four Sha (West), it will also lead to the judgment that there are more than X Wind tiles, so bot will kokushi musou(thirteen orphans)

在实际运行中，如果你有连续的三张nan(south)，或者4张sha(west)，这也会导致判断大于x张wind tile，从而进行国士无双

**Comment by Jimboom7** [comment]
> In actual operation, if you have three consecutive Nan (South), or four Sha (West), it will also lead to the judgment that there are more than X Wind tiles, so bot will kokushi musou(thirteen orphans)

This should not be the case. The bot only counts unique tiles for the kokushi musou decision. Multiple copies of the same tile are ignored.
