### ISSUE TITLE
Is there a possibility of being banned for using the help mode?

### ISSUE THREAD

**Issue by NehalemJong** [Jimboom7/AlphaJong#83]
I think that the BOT is detected because of the direct communication with the server using the app.NetAgent.
So I think that if the BOT is activated in help mode, it will not be BANNED.

Or is it because of the use of view.DesktopMgr to perform actions that are impossible for humans?

**Comment by Jimboom7** [comment]
I can't give a definite answer on that. But there have been no reports of bans related to the help mode (and I tried that myself recently - no problems).  
The exact reason that leads to the bans is unclear. I suspect that it's related to using the bot for an excessive amount of time. It is likely that the game is able to detect "monotonous" gameplay over a long period of time.  
The NetAgent code should not be a problem - in the end it's the same code that is run when you click on a button or perform an action in the game. Same for the DesktopMgr functions.  
Whatever the reason: I think using the help mode is safe, but I can't give a guarantee on that.

**Comment by TRSWNCA** [comment]
I suppose the detection may read some data in localStorage, which is easy and accurate. So a better way is to make a pure extension not use the easily detected data.

**Comment by Jimboom7** [comment]
I added a section to the readme that explains how to avoid a ban for sure.
