### ISSUE TITLE
drop card time pattern must be random. AI need change 

### ISSUE THREAD

**Issue by trainbyu** [Jimboom7/AlphaJong#89]
Because [AUTO MODE] AI always same pattern same timing drop a card.

this playing pattern game team can be caught using external programs regardless of 24 hours of play.

When other person Riichi, needs to acting like worried and thinking. 

In such a situation, I think the type of throwing away the card with randomness should be added in 4-5 seconds or 6 seconds.

  so that he can be considered a human being.

**Comment by Liujunhua007** [comment]
The speed is relevant to cpu.As the game goes on, it will be slower and slower.

**Comment by Jimboom7** [comment]
The delay is already a bit random.  
Anyway, if you are worried about bans I just added a section to the readme that explains how to be safe. [Chinese instructions are here](https://github.com/Avenshy/majsoul_mod_plus).
