### ISSUE TITLE
Parameters of the AI

### ISSUE THREAD

**Issue by CruncyKukie** [Jimboom7/AlphaJong#92]
![image](https://user-images.githubusercontent.com/93718509/193365222-097408c6-5490-4c86-a9f4-58b7329d52ec.png)
Three-player mahjong is doing very fine.

![image](https://user-images.githubusercontent.com/93718509/193365353-bbebfc8d-2a0a-47ab-949c-48a705a5b09d.png)
But in classic Four-player mahjong, It can't even win once in bronze match .-. ( that No.1 is not played by AI )

**Comment by Liujunhua007** [comment]
Is there a possibility of luck or game system sanctions?

**Comment by CruncyKukie** [comment]
hmm, i think you're right, but isn't it too unlucky that it didn't won a single game out of 20 match .-.

**Comment by Liujunhua007** [comment]
Maybe another time try it will be different....The su is too lower in the picture,which means luck is bad to a degreed.^_~

**Comment by CruncyKukie** [comment]
alrighty
