### ISSUE TITLE
两个小号被永封了/Two accounts are banned

### ISSUE THREAD

**Issue by Jiangdonganxia** [Jimboom7/AlphaJong#97]
我一个开半自动，一个没开两个都被封了。其他评论里的老哥也是今天被封了，应该是被抓脚本特征了，例如切牌时间/I also saw the ban in other messages, possibly because the script features are marked

**Comment by Jimboom7** [comment]
请参考[雀魂mod_plus](https://github.com/Avenshy/majsoul_mod_plus)的续命说明。
